### ISSUE TITLE
Docker login fails with missing errors

### ISSUE THREAD

**Issue by kushthedude** [Azure/docker-login#22]
I am using azure/docker-login for quite a while but now it is failing with a weird error of missing username while login, whereas I have already configured the secrets.

A more intriguing fact is that this error is only shown in the case of the event pull_request but when a commit is made to master the login is a success.

Logs & Pull Request :
https://github.com/layer5io/meshery/pull/1952/checks?check_run_id=1430739345

**Comment by jeffwilcox** [comment]
Did you grab the latest commit ID from the action? Looks like environment variable updates broke this... I moved to the latest version, but now we get errors about not finding the module `@actions/core`... hmm.

Here's the error I see after moving to azure/docker-login@944f3176a9cfe29e1c53e92dff83e4f8c6eef52b

Probably needs to be added to the package.json file?

```
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/azure/docker-login/944f3176a9cfe29e1c53e92dff83e4f8c6eef52b/lib/login.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/_actions/azure/docker-login/944f3176a9cfe29e1c53e92dff83e4f8c6eef52b/lib/login.js:11:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/azure/docker-login/944f3176a9cfe29e1c53e92dff83e4f8c6eef52b/lib/login.js'
  ]
}
```

**Comment by kushthedude** [comment]
We switched to dockerhub login action as soon as we experienced error with the azure, but do let me know if the action gets fixed again 🙂

**Comment by shigupt202** [comment]
@jeffwilcox Could you share the version that you are specifying with the action? Ideally it should be v1.
@kushthedude Could you share the logs of failing workflow? The current link doesn't seem to have any logs.

**Comment by thesattiraju** [comment]
Closing this stale issue. If the problem still persists fee free to re-open this. 😃
